### ISSUE TITLE
Vector Range

### ISSUE THREAD

**Issue by Kazuma-47** [bas-boop/Feature-vault#15]
**Is your feature request related to a problem?**
this is not related to a problem but a idea that might make it easier for the users to edit values.

**Describe the solution you'd like**
for some vectors there might be a maximum or minimal value that you would want to use. i would like to see a option that helps with editing vector 2/3 values using a slider in the editor.

**Comment by bas-boop** [comment]
That's a good idea. I like it so much this will be in the first release of Feature-vault.
